### ISSUE TITLE
Cleaning repo

### ISSUE THREAD

**Issue by rodolfo-viana** [okfn-brasil/notebooks#11]
**What is the problem?** 

As this repo is designed to people who wants to learn and develop data science skills, I believe some files are not necessary and may confuse newcomers. For example `deliver` and `test` folders, as well as `.travis.yml` and `.pyup.yml`. Or are they necessary for this repo? If not, how about deleting them?

**How can this be addressed?**

If @jtemporal and @cuducos agree, I suggest we keep only notebooks and necessary codes to assist users, and delete everything else.

**Who could help with this issue?**

JT and Cuducos.

**Comment by cuducos** [comment]
We can safely remove `.pyup.yml`. As for `.travis.yml` it is supposed to run a test we've written to assure every contribution has the `.html` and `.py` version — very useful for code reviewing. So I'd keep it (and enable Travis CI).

**Comment by cuducos** [comment]
[Activated](https://travis-ci.org/okfn-brasil/notebooks) ; )

**Comment by jtemporal** [comment]
What I think we should do:
- Remove `.pyup.yml` file
- Remove `src` folder (since the same content [is available in the okfn-brasil/serenata-de-amor repo](https://github.com/okfn-brasil/serenata-de-amor/tree/master/research))
- move all the jupyter notebooks from `notebooks/deliver` and `notebooks/develop` to `notebooks` (and delete the empty folders) 
- move the `Dockerfile`, the `requirements.txt` and the `jupyter_notebook_config.py` to the project root 
- create the missing `setup` file
- update the `Dockerfile` to the new structure

**Comment by rodolfo-viana** [comment]
+1

Would you do that, @jtemporal?

**Comment by jtemporal** [comment]
I'll leave the `setup` to a new issue, will open it up later :wink:
